"""Canonical team names and cross-provider name resolution.

Different sources spell the same club differently: football-data.co.uk writes
"Man United", StatsBomb writes "Manchester United", and neither matches the club's
own preferred styling ("Manchester United FC"). Modelling treats those as three
different teams, which quietly corrupts every rating.

The registry below pins one canonical name per club. Aliases are explicit and
hand-checked rather than generated by fuzzy matching, because automatic fuzzy
matching on a list of 20 team names will eventually merge two clubs that share a
word -- and a silent merge is much harder to notice than a missing alias.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

from predict_football.data.identifiers import make_team_id, normalise_whitespace, slugify

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class Team:
    """A club or national team with its canonical identity.

    Attributes:
        canonical_name: The single name used everywhere in this project.
        aliases: Known alternative spellings from other sources. Keys and values
            are compared after slugification.
        league_keys: Competitions this team appears in.
        short_name: Common short form, used in the UI and narrative text.
        country: Governing country, where meaningful.
    """

    canonical_name: str
    aliases: tuple[str, ...] = field(default_factory=tuple)
    league_keys: tuple[str, ...] = field(default_factory=tuple)
    short_name: str | None = None
    country: str | None = None

    @property
    def team_id(self) -> str:
        """Stable identifier derived from the canonical name."""
        return make_team_id(self.canonical_name)


def _england_top_flight() -> tuple[Team, ...]:
    """Build the Premier League team registry as of the 2025/26 season.

    Returns:
        One :class:`Team` per club.
    """
    raw: tuple[tuple[str, tuple[str, ...], str], ...] = (
        ("Arsenal", (), "England"),
        ("Aston Villa", ("Villa",), "England"),
        ("Bournemouth", ("AFC Bournemouth",), "England"),
        ("Brentford", (), "England"),
        ("Brighton & Hove Albion", ("Brighton", "Brighton and Hove Albion"), "England"),
        ("Burnley", (), "England"),
        ("Chelsea", (), "England"),
        ("Crystal Palace", ("Palace",), "England"),
        ("Everton", (), "England"),
        ("Fulham", (), "England"),
        ("Ipswich Town", ("Ipswich",), "England"),
        ("Leeds United", ("Leeds",), "England"),
        ("Liverpool", (), "England"),
        ("Manchester City", ("Man City",), "England"),
        ("Manchester United", ("Man United", "Man Utd", "Man U"), "England"),
        ("Newcastle United", ("Newcastle", "Newcastle Utd"), "England"),
        ("Nottingham Forest", ("Forest", "Nottm Forest", "Nott'm Forest"), "England"),
        ("Sunderland", (), "England"),
        ("Tottenham Hotspur", ("Spurs", "Tottenham", "Tottenham Hotspur FC"), "England"),
        ("West Ham United", ("West Ham", "West Ham Utd"), "England"),
        ("Wolverhampton Wanderers", ("Wolves", "Wolves FC"), "England"),
        ("Wigan Athletic", ("Wigan",), "England"),
        ("West Bromwich Albion", ("West Brom", "WBA"), "England"),
        ("Sheffield United", ("Sheffield Utd",), "England"),
        ("Sheffield Wednesday", ("Sheffield Weds", "Sheffield Weds FC"), "England"),
        ("Huddersfield Town", ("Huddersfield",), "England"),
        ("Cardiff City", ("Cardiff",), "England"),
        ("Swansea City", ("Swansea",), "England"),
        ("Birmingham City", ("Birmingham",), "England"),
        ("Blackburn Rovers", ("Blackburn",), "England"),
        ("Hull City", ("Hull",), "England"),
        ("Coventry City", ("Coventry",), "England"),
        ("Luton Town", ("Luton",), "England"),
        ("Watford", (), "England"),
        ("Norwich City", ("Norwich",), "England"),
        # Leicester and Southampton each spent part of the ingested window in the
        # top flight and part below it. They are listed here rather than with the
        # current squad because modelling needs one identity per club across
        # seasons, not one per division.
        ("Leicester City", ("Leicester",), "England"),
        ("Southampton", ("Soton",), "England"),
        # Clubs present in the Championship window that a longer backtest will
        # reach. Present so promotion and relegation continuity stays checkable.
        ("QPR", ("Queens Park Rangers",), "England"),
        ("Reading", (), "England"),
        ("Middlesbrough", ("Middlesboro", "Boro"), "England"),
        ("Stoke City", ("Stoke",), "England"),
        ("Preston North End", ("Preston",), "England"),
    )
    return tuple(
        Team(
            canonical_name=name,
            aliases=aliases,
            league_keys=("ENG_PL", "ENG_CHAMPIONSHIP"),
            short_name=aliases[0] if aliases else name,
            country=country,
        )
        for name, aliases, country in raw
    )


def _spain_la_liga() -> tuple[Team, ...]:
    """Build the La Liga team registry.

    Returns:
        One :class:`Team` per club.
    """
    raw: tuple[tuple[str, tuple[str, ...]], ...] = (
        ("Real Madrid", ("Real Madrid CF",)),
        ("Barcelona", ("FC Barcelona", "Barca")),
        ("Atlético Madrid", ("Atletico Madrid", "Atlético de Madrid", "Atletico de Madrid", "Ath Madrid")),
        ("Athletic Club", ("Athletic Bilbao", "Athletic Club de Bilbao", "Ath Bilbao", "Ath. Bilbao")),
        ("Real Sociedad", ("Sociedad",)),
        ("Real Betis", ("Betis",)),
        ("Villarreal", ("Villarreal CF",)),
        ("Valencia", ("Valencia CF",)),
        ("Sevilla", ("Sevilla FC",)),
        ("Girona", ("Girona FC",)),
        ("Osasuna", ("CA Osasuna",)),
        ("Celta Vigo", ("Celta de Vigo", "Celta")),
        ("Rayo Vallecano", ("Rayo", "Vallecano")),
        ("Mallorca", ("RCD Mallorca",)),
        ("Getafe", ()),
        ("Alavés", ("Alaves", "Deportivo Alavés")),
        ("Espanyol", ()),
        ("Levante", ()),
        ("Elche", ()),
        ("Real Oviedo", ("Oviedo",)),
        ("UD Almería", ("Almeria", "Almería", "UD Almeria")),
        ("Cádiz", ("Cadiz",)),
        ("Granada", ("Granada CF",)),
        ("Las Palmas", ("Las Palmas CF",)),
        # Reserve sides are deliberately separate clubs: Real Betis Balompié is
        # Real Betis B, and merging the two would attribute second-tier results to
        # a first-tier side.
        ("Real Betis Balompié", ("Betis Balompié", "Real Betis B")),
    )
    return tuple(
        Team(canonical_name=name, aliases=aliases, league_keys=("ESP_LA_LIGA",), country="Spain")
        for name, aliases in raw
    )


def _italy_serie_a() -> tuple[Team, ...]:
    """Build the Serie A team registry.

    Returns:
        One :class:`Team` per club.
    """
    raw: tuple[tuple[str, tuple[str, ...]], ...] = (
        ("Inter Milan", ("Internazionale", "Inter")),
        ("AC Milan", ("Milan",)),
        ("Juventus", ("Juve",)),
        ("Napoli", ("SSC Napoli",)),
        ("AS Roma", ("Roma",)),
        ("Lazio", ("SS Lazio",)),
        ("Atalanta", ()),
        ("Fiorentina", ()),
        ("Bologna", ()),
        ("Torino", ()),
        ("Udinese", ()),
        ("Genoa", ()),
        ("Empoli", ()),
        ("Cagliari", ()),
        ("Hellas Verona", ("Verona",)),
        ("Sassuolo", ()),
        ("Lecce", ()),
        ("Parma", ()),
        ("Como", ()),
        ("Venezia", ()),
    )
    return tuple(
        Team(canonical_name=name, aliases=aliases, league_keys=("ITA_SERIE_A",), country="Italy")
        for name, aliases in raw
    )


def _germany_bundesliga() -> tuple[Team, ...]:
    """Build the Bundesliga team registry.

    Returns:
        One :class:`Team` per club.
    """
    raw: tuple[tuple[str, tuple[str, ...]], ...] = (
        ("Bayern Munich", ("FC Bayern München", "Bayern Munchen", "Bayern Munich")),
        ("Borussia Dortmund", ("Dortmund", "BVB")),
        ("RB Leipzig", ("Leipzig",)),
        ("Bayer Leverkusen", ("Leverkusen",)),
        ("VfB Stuttgart", ("Stuttgart",)),
        ("Eintracht Frankfurt", ("Frankfurt",)),
        ("Borussia Mönchengladbach", ("Borussia Monchengladbach", "Gladbach")),
        ("Wolfsburg", ("VfL Wolfsburg",)),
        ("Freiburg", ("SC Freiburg",)),
        ("Hoffenheim", ("TSG Hoffenheim",)),
        ("Werder Bremen", ("Bremen",)),
        ("Union Berlin", ("1. FC Union Berlin", "Union")),
        ("Mainz 05", ("Mainz",)),
        ("FC Augsburg", ("Augsburg",)),
        ("St. Pauli", ("St Pauli", "FC St. Pauli")),
        ("Holstein Kiel", ("Kiel",)),
        ("Heidenheim", ("1. FC Heidenheim",)),
        ("Stuttgart II", ()),
    )
    return tuple(
        Team(canonical_name=name, aliases=aliases, league_keys=("GER_BUNDESLIGA",), country="Germany")
        for name, aliases in raw
    )


def _france_ligue_1() -> tuple[Team, ...]:
    """Build the Ligue 1 team registry.

    Returns:
        One :class:`Team` per club.
    """
    raw: tuple[tuple[str, tuple[str, ...]], ...] = (
        ("Paris Saint-Germain", ("PSG", "Paris SG", "Paris Saint Germain")),
        ("Marseille", ("Olympique Marseille", "OM")),
        ("Monaco", ("AS Monaco",)),
        ("Lyon", ("Olympique Lyonnais", "OL")),
        ("Lille", ("LOSC Lille",)),
        ("Nice", ("OGC Nice",)),
        ("Lens", ("RC Lens",)),
        ("Rennes", ("Stade Rennais",)),
        ("Strasbourg", ("RC Strasbourg",)),
        ("Brest", ("Stade Brestois",)),
        ("Toulouse", ("Toulouse FC",)),
        ("Auxerre", ("AJ Auxerre",)),
        ("Nantes", ("FC Nantes",)),
        ("Angers", ("Angers SCO",)),
        ("Le Havre", ("Havre",)),
        ("Reims", ("Stade de Reims",)),
        ("Saint-Étienne", ("Saint-Etienne", "AS Saint-Etienne")),
        ("Metz", ("FC Metz",)),
    )
    return tuple(
        Team(canonical_name=name, aliases=aliases, league_keys=("FRA_LIGUE_1",), country="France")
        for name, aliases in raw
    )


def _afcon_teams() -> tuple[Team, ...]:
    """Build national-team entries for the Africa Cup of Nations.

    Returns:
        One :class:`Team` per nation.
    """
    raw: tuple[tuple[str, tuple[str, ...]], ...] = (
        ("Algeria", ("Algeria",)),
        ("Angola", ()),
        ("Benin", ("Bénin",)),
        ("Botswana", ()),
        ("Burkina Faso", ()),
        ("Cameroon", ()),
        ("Cape Verde", ("Cabo Verde",)),
        ("Côte d'Ivoire", ("Ivory Coast", "Cote d'Ivoire")),
        ("DR Congo", ("Democratic Republic of the Congo", "Zaire")),
        ("Egypt", ()),
        ("Equatorial Guinea", ()),
        ("Gabon", ()),
        ("Gambia", ()),
        ("Ghana", ()),
        ("Guinea", ()),
        ("Guinea-Bissau", ()),
        ("Kenya", ()),
        ("Mali", ()),
        ("Mauritania", ()),
        ("Morocco", ()),
        ("Mozambique", ()),
        ("Namibia", ()),
        ("Nigeria", ()),
        ("Senegal", ()),
        ("South Africa", ()),
        ("Sudan", ()),
        ("Tanzania", ()),
        ("Tunisia", ()),
        ("Uganda", ()),
        ("Zambia", ()),
    )
    return tuple(
        Team(canonical_name=name, aliases=aliases, league_keys=("INT_AFCON",), country=name)
        for name, aliases in raw
    )


#: Every team we know about.
TEAMS: tuple[Team, ...] = (
    _england_top_flight()
    + _spain_la_liga()
    + _italy_serie_a()
    + _germany_bundesliga()
    + _france_ligue_1()
    + _afcon_teams()
)


class TeamResolver:
    """Resolves source-specific team spellings to canonical identities.

    Built once at import and reused; construction is cheap but not free, and it
    is read-only afterwards.

    Args:
        teams: Registry to resolve against. Defaults to :data:`TEAMS`.

    Example:
        >>> resolver = TeamResolver()
        >>> resolver.resolve("Man United")
        'Manchester United'
        >>> resolver.resolve("Manchester United")
        'Manchester United'
    """

    def __init__(self, teams: tuple[Team, ...] = TEAMS) -> None:
        self._by_key: dict[str, Team] = {}
        for team in teams:
            for name in (team.canonical_name, *team.aliases):
                self._by_key[self._key(name)] = team

    @staticmethod
    def _key(name: str) -> str:
        """Normalise a name into a lookup key.

        Args:
            name: Raw team name from any source.

        Returns:
            A comparable lowercase form with punctuation removed.
        """
        return slugify(name).replace(" fc", "").replace(" cf", "").replace(" afc", "").strip()

    def resolve(self, raw_name: str) -> str | None:
        """Resolve a source name to its canonical form.

        Args:
            raw_name: Team name exactly as the source published it.

        Returns:
            The canonical name, or ``None`` when the name is unknown. Returning
            ``None`` rather than guessing is deliberate: a wrong merge is far
            more damaging than a visible gap.
        """
        if raw_name is None:
            return None
        cleaned = normalise_whitespace(str(raw_name))
        if not cleaned:
            return None
        team = self._by_key.get(self._key(cleaned))
        return team.canonical_name if team else None

    def resolve_or_pass_through(self, raw_name: str) -> str:
        """Resolve a name, falling back to the tidied original when unknown.

        Used on ingest so a new club is not silently dropped. The fact that a
        name passed through unrecognised is recorded in the database so the gap
        is visible rather than silent.

        Args:
            raw_name: Team name as published by the source.

        Returns:
            Canonical name, or whitespace-normalised original.
        """
        resolved = self.resolve(raw_name)
        if resolved is not None:
            return resolved
        tidied = normalise_whitespace(str(raw_name))
        logger.info("Unrecognised team name %r; stored as-is and flagged for review", raw_name)
        return tidied

    def is_known(self, raw_name: str) -> bool:
        """Report whether a name resolves to a registered team.

        Args:
            raw_name: Team name as published by a source.

        Returns:
            True if the name is in the registry.
        """
        return self.resolve(raw_name) is not None

    def team_id(self, raw_name: str) -> str:
        """Return the canonical team identifier for a source name.

        Args:
            raw_name: Team name as published by a source.

        Returns:
            Slug identifier for the resolved or tidied team.
        """
        return make_team_id(self.resolve_or_pass_through(raw_name))

    def __len__(self) -> int:
        return len(self._by_key)
